<a href="https://colab.research.google.com/github/jjunga1203/Books/blob/master/test_kogpt2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
dir_path = './drive/MyDrive/final_prj/data/'
cwd = os.getcwd()
cwd

'/content'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
ls ./drive/MyDrive/final_prj/data/

'02)웰니스_대화_스크립트_데이터셋.xlsx'                5차년도.csv
 1_0928G1A1_0930G1A1_T1_1D04T0160C000125_003178.json  '감성대화말뭉치(최종데이터)_Training.json'
 1_6617G2A1_6614G2A1_T1_1D06T0219C000258_030319.wav   '감성대화말뭉치(최종데이터)_Training.xlsx'
 4차년도.csv                                           나무_7_남_00242.json
 5차년도_2차.csv                                       웰니스_대화_스크립트_데이터셋.xlsx


In [ ]:
import pandas as pd
import json

In [ ]:
f = open('./Empathy_기쁨_부모자녀_조손_1.json')
data = json.load(f)

In [ ]:
data.keys()

dict_keys(['info', 'utterances'])

In [ ]:
# data['info'].keys()
info = [data['info']['category'], data['info']['listener_behavior'], data['info']['relation'], data['info']['situation'], data['info']['speaker_emotion'], data['info']['speaker_relation']]
cat1 = info[0]
cat2 = ('/').join(info[1])
cat3 = info[4]
relation = info[5]
subject = info[3]

In [ ]:
data['utterances']
json_df = pd.json_normalize(data, record_path=['utterances'])
json_df['category1'] = cat1
json_df['category2'] = cat2
json_df['category3'] = cat3
json_df['relation'] = relation
json_df['subject'] = subject
json_df.drop(labels=['listener_empathy', 'speaker_changeEmotion', 'utterance_id'], axis=1, inplace=True)
json_df

role  terminate                                               text  \
0    speaker      False           엄마, 아기가 태어나니까 내가 부모로서 해야 할 게 참 많은 것 같아요.   
1   listener      False                       그렇지? 아기 키우는 게 여간 어려운 일이 아니야.   
2    speaker      False      어제 평소보다도 격하게 막 온몸을 써가면서 울더라고요. 얼마나 당황했는지 몰라요.   
3   listener      False            배가 고파서 그랬던 것 아닐까? 아기들은 배가 고프면 몸부림을 친단다.   
4    speaker      False           맞아요. 젖을 물려주니 금세 뚝 그쳤어요. 난 분명히 순했을 것 같은데.   
5   listener      False          말도 마. 네가 얼마나 까탈스러웠는데. 우리 손주가 내 딸을 빼다 박았네.   
6    speaker      False         잠도 못 자고 우는 아이 달래랴 수유하랴 머리카락이 다 빠지는 줄 알았어요.   
7   listener      False                   네가 어른 노릇, 부모 노릇을 하느라 고생이 정말 많구나.   
8    speaker      False  그러면서 엄마 생각이 많이 났어요. 엄마는 직장까지 다니면서 나를 키우느라 얼마나 ...   
9   listener      False  우리 딸이 엄마가 되더니 철이 들었네. 하지만 네가 웃어주면 세상 모든 시름이 사라...   
10   speaker      False         저는 너무 아무 준비 없이 아기를 가져서 앞으로 배워야 할 게 너무 많아요.   
11  listener      False   공부하듯이 배우는 것이 아니라, 자연스레 익히게 될 거야. 너무 미리 걱정할 것 없어.   
12   speaker      False  아기를 낳고 나니 새로운 세상을 선물 받은 기분이 들어요. 기쁘고 설레고 걱정되고 ...   
13  listener      False     새로운 세상에 온 걸 환영한다, 내 딸. 엄마로서의 인생은 정말 선물 그 자체란다.   
14   speaker       True                               앞으로 많이 가르쳐 주세요, 선배님.   

   category1    category2 category3 relation                        subject  
0     공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
1     공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
2     공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
3     공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
4     공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
5     공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
6     공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
7     공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
8     공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
9     공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
10    공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
11    공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
12    공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
13    공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.  
14    공감형 대화  격려/조언/동조/위로        기쁨       자녀  아이가 태어나니 부모가 배우고 익혀야 할 것이 많다.

In [ ]:
# df = pd.read_csv(dir_path+'4차년도.csv', encoding='CP949')

In [ ]:
# df.info()

In [ ]:
# emotion_df = df[['발화문', '상황']]

In [ ]:
# emotion_df.info()

In [ ]:
orign = pd.read_excel(dir_path + '감성대화말뭉치(최종데이터)_Training.xlsx', index_col=0)


In [ ]:
df_copy1 = orign.copy()
df_copy2 = orign.copy()

In [ ]:
df_copy1.drop(labels=['연령', '성별','상황키워드','신체질환', '사람문장2', '시스템문장2', '사람문장3', '시스템문장3'], axis=1, inplace=True)

In [ ]:
df_copy2.drop(labels=['연령', '성별','상황키워드','신체질환', '사람문장1', '시스템문장1', '사람문장3', '시스템문장3'], axis=1, inplace=True)

In [ ]:
df_copy2.tail()

감정_대분류 감정_소분류                                              사람문장2  \
51626     분노    성가신                   아무것도 할 수 없는 내가 무가치하게 느껴지고 실망스러워.   
51627     불안    초조한          마음 같아서는 다 할 수 있는 일인데 이젠 몸이 안 따라와 주니 화만 나.   
51628     상처    희생된  주변 사람들은 다 노후 준비도 잘해두었던데 난 어떻게 해야 할지 모르겠어. 막막하기...   
51629     불안  걱정스러운             이제 할 수 있는 일도 없고 이렇게 힘들게 사는 게 불만스럽기만 해.   
51630     상처   배신당한             사람들을 만나는 것이 어려워. 자꾸 사람들을 의심하게만 되고 말이야.   

                                 시스템문장2  
51626      지금 할 수 있는 가장 합리적인 행동은 무엇인가요?  
51627     어떻게 하면 지금의 기분을 나아지게 할 수 있을까요?  
51628  지금의 상황에서 할 수 있는 가장 좋은 행동이 무엇일까요?  
51629  지금의 감정을 나아지게 할 수 있는 어떤 방법이 있을까요?  
51630   어떻게 하면 지금의 상황에 변화를 만들어낼 수 있을까요?

In [ ]:
df_copy1.tail()

감정_대분류 감정_소분류                                              사람문장1  \
51626     분노    성가신     나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해. 능력도 없고.   
51627     불안    초조한        몸이 많이 약해졌나 봐. 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나.   
51628     상처    희생된   이제 어떻게 해야 할지 모르겠어. 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼.   
51629     불안  걱정스러운  몇십 년을 함께 살았던 남편과 이혼했어. 그동안의 세월에 배신감을 느끼고 너무 화가 나.   
51630     상처   배신당한  남편과 결혼한 지 사십 년이야. 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라져.   

                                      시스템문장1  
51626     경제적인 문제 때문에 막막하시군요. 마음이 편치 않으시겠어요.  
51627  건강에 대한 어려움 때문에 기분이 좋지 않으시군요. 속상하시겠어요.  
51628          노후 준비에 대한 어려움 때문에 걱정이 많으시겠어요.  
51629                   가족과의 문제 때문에 속상하시겠어요.  
51630        대인관계에 대한 어려움 때문에 걱정되시고 속상하시겠어요.

In [ ]:
# 두 DataFrame을 번갈아가며 합치기
result_rows = [row for pair in zip(df_copy1.values, df_copy2.values) for row in pair]
result_df = pd.DataFrame(result_rows, columns=df_copy1.columns)
result_df['label'] =  result_df['감정_대분류'] + '/' + result_df['감정_소분류']
result_df.drop(labels=['감정_대분류', '감정_소분류'], axis=1, inplace=True)
result_df.columns = ['question', 'response', 'label']

# 열 순서 변경
new_order = ['label','question', 'response']  # 변경하고 싶은 열 순서
result_df = result_df.reindex(columns=new_order)

result_df.head()

label                                           question  \
0  분노/노여워하는                          일은 왜 해도 해도 끝이 없을까? 화가 난다.   
1  분노/노여워하는                그냥 내가 해결하는 게 나아. 남들한테 부담 주고 싶지도 않고.   
2  분노/노여워하는     이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.   
3  분노/노여워하는   최대한 지출을 억제해야겠어. 월급이 줄어들었으니 고정지출을 줄일 수밖에 없을 것 같아.   
4  분노/노여워하는  회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...   

                                            response  
0                        많이 힘드시겠어요. 주위에 의논할 상대가 있나요?  
1     혼자 해결하기로 했군요. 혼자서 해결하기 힘들면 주위에 의논할 사람을 찾아보세요.   
2           급여가 줄어 속상하시겠어요. 월급이 줄어든 것을 어떻게 보완하실 건가요?  
3                           월급이 줄어든 만큼 소비를 줄일 계획이군요.  
4  회사 동료 때문에 스트레스를 많이 받는 것 같아요. 문제 해결을 위해 어떤 노력을 ...

In [ ]:
result_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103260 entries, 0 to 103259
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   label     103260 non-null  object
 1   question  103260 non-null  object
 2   response  103260 non-null  object
dtypes: object(3)
memory usage: 2.4+ MB


In [ ]:
# df2.info()

In [ ]:
df3 = pd.read_excel(dir_path + '웰니스_대화_스크립트_데이터셋.xlsx')

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5231 entries, 0 to 5230
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   구분      5231 non-null   object
 1   유저      5231 non-null   object
 2   챗봇      1034 non-null   object
dtypes: object(3)
memory usage: 122.7+ KB


In [ ]:
df3.columns = ['label', 'question', 'response']
df3.fillna('', inplace=True)
df3.head()

label                                         question  \
0  감정/감정조절이상  제 감정이 이상해진 것 같아요. 남편만 보면 화가 치밀어 오르고 감정 조절이 안되요.   
1  감정/감정조절이상                         더 이상 내 감정을 내가 컨트롤 못 하겠어.   
2  감정/감정조절이상                      하루종일 오르락내리락 롤러코스터 타는 기분이에요.   
3  감정/감정조절이상                                꼭 롤러코스터 타는 것 같아요.   
4  감정/감정조절이상                       롤러코스터 타는 것처럼 기분이 왔다 갔다 해요.   

                                  response  
0          감정이 조절이 안 될 때만큼 힘들 때는 없는 거 같아요.  
1                   저도 그 기분 이해해요. 많이 힘드시죠?  
2  그럴 때는 밥은 잘 먹었는지, 잠은 잘 잤는지 체크해보는 것도 좋아요.  
3                                           
4

In [ ]:
## 위 두개의 데이터 프레임 합치기
# 두 DataFrame을 합치기
concat_df = pd.concat([df3, result_df], axis=0, ignore_index=True)
concat_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108491 entries, 0 to 108490
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   label     108491 non-null  object
 1   question  108491 non-null  object
 2   response  108491 non-null  object
dtypes: object(3)
memory usage: 2.5+ MB


In [ ]:
!pip install pytorch_lightning

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 802.2/802.2 kB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 868.8/868.8 kB 18.1 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
ERROR: Operation cancelled by user


In [ ]:
### https://a2ran.github.io/chatbot/kogpt2-chatbot/  참고할 만 하다 (웰니스 대화 스크립트 데이터셋)
### https://github.com/a2ran/kogpt2-chatbot/blob/main/code.ipynb

### 그림일기로 구현하는 예제인듯
### https://velog.io/@minjungh63/%EC%9E%90%EC%97%B0%EC%96%B4-%EC%B2%98%EB%A6%AC-%EB%AA%A8%EB%8D%B8-q8fdrm1k

In [ ]:
# !pip install transformers

import tensorflow as tf
from transformers import AutoTokenizer
from transformers import TFGPT2LMHeadModel

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import tqdm


In [ ]:
tokenizer = AutoTokenizer.from_pretrained('skt/kogpt2-base-v2', bos_token='</s>', eos_token='</s>', pad_token='<pad>')
model = TFGPT2LMHeadModel.from_pretrained('skt/kogpt2-base-v2', from_pt=True)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFGPT2LMHeadModel: ['lm_head.weight', 'transformer.h.11.attn.masked_bias', 'transformer.h.2.attn.masked_bias', 'transformer.h.1.attn.masked_bias', 'transformer.h.10.attn.masked_bias', 'transformer.h.3.attn.masked_bias', 'transformer.h.5.attn.masked_bias', 'transformer.h.8.attn.masked_bias', 'transformer.h.9.attn.masked_bias', 'transformer.h.6.attn.masked_bias', 'transformer.h.4.attn.masked_bias'

In [ ]:
def tokenize_df():
    # 질문, 레이블 응답 문장을 불러옵니다.
    for question, label, response in zip(concat_df.question.to_list(),
                                         concat_df.label.to_list(), concat_df.response.to_list()):
        # 문장의 BOS token : </s>
        bos_token = [tokenizer.bos_token_id]
        # 문장의 EOS token : </s>
        eos_token = [tokenizer.eos_token_id]

        #문장 구조 : BOS + 질문 + (토큰으로 구분) + 레이블 + (토큰으로 구분) + 응답 + EOS
        sentence = tokenizer.encode('<unused0>' + question + '<unused1>' + label + '<unused2>' + response)

        yield bos_token + sentence + eos_token

In [ ]:
batch_size = 32

# def 함수를 적용한 tf dataset을 만듭니다.
dataset = tf.data.Dataset.from_generator(tokenize_df, output_types = tf.int32)

# batch에서 가장 긴 문장을 기준으로 zero-padding을 진행합니다.
dataset = dataset.padded_batch(batch_size = batch_size, padded_shapes=(None,),
                               padding_values = tokenizer.pad_token_id)

for batch in dataset:
  print(batch)
  print(tokenizer.decode(batch[0]))
  break


tf.Tensor(
[[    1     9  9037 ...     3     3     3]
 [    1     9  9267 ...     3     3     3]
 [    1     9 12557 ...     3     3     3]
 ...
 [    1     9 17932 ...     3     3     3]
 [    1     9 11403 ...     3     3     3]
 [    1     9 12980 ...     3     3     3]], shape=(32, 54), dtype=int32)
</s><unused0> 제 감정이 이상해진 것 같아요. 남편만 보면 화가 치밀어 오르고 감정 조절이 안되요.<unused1> 감정/감정조절이상<unused2> 감정이 조절이 안 될 때만큼 힘들 때는 없는 거 같아요.</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>


In [ ]:
EPOCHS = 5
adam = tf.keras.optimizers.Adam(learning_rate = 3e-5, epsilon=1e-08)
steps = len(concat_df) // batch_size + 1

In [ ]:
# dataset을 batch_size으로 나눈 batch에서 loss를 계산한 후
# tf.GradientTape으로 gradient을 계산하고
# 계산한 gradient을 통해 adam(model)을 업데이트합니다.

for epoch in range(EPOCHS):
    train_loss = 0

    try:
        for batch in tqdm.notebook.tqdm(dataset, total = steps):
            try:
                with tf.GradientTape() as tape:
                    result = model(batch, labels = batch)
                    loss = result[0]
                    batch_loss = tf.reduce_mean(loss, -1)

                grads = tape.gradient(batch_loss, model.trainable_variables)
                adam.apply_gradients(zip(grads, model.trainable_variables))
                train_loss += batch_loss / steps

            except Exception as e:
                print("TRY 1: Exception occurred:", str(e))

    except Exception as e:
        print("TRY 2: Exception occurred:", str(e))

  0%|          | 0/3391 [00:00<?, ?it/s]

In [ ]:
# save fine-tuned tokenizer & model

tokenizer.save_pretrained('chatbot')
model.save_pretrained('chatbot')

In [ ]:
# load fine-tuned model

tokenizer = AutoTokenizer.from_pretrained('chatbot', bos_token='</s>', eos_token='</s>', pad_token='<pad>')
model = TFGPT2LMHeadModel.from_pretrained('chatbot')

All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at chatbot.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [ ]:
def chatbot(text):
    # input sentence : "질문" / 레이블 + 응답
    sentence = '<unused0>' + text + '<unused1>'
    tokenized = [tokenizer.bos_token_id] + tokenizer.encode(sentence)
    tokenized = tf.convert_to_tensor([tokenized])

    # 질문 문장으로 "레이블 + 응답" 토큰 생성
    result = model.generate(tokenized, min_length = 50, max_length = 200, repetition_penalty = 0.8,
                            do_sample = True, no_repeat_ngram_size = 3, temperature = 0.01,
                            top_k = 5)

    output = tokenizer.decode(result[0].numpy().tolist())

    response = output.split('<unused1> ')[1]
    # 레이블 토큰 출력
    label = response.split('<unused2> ')[0]
    # 응답 토큰 생성
    response = response.split('<unused2> ')[1].replace('</s>', '')

    return label, response

In [ ]:
label, ans = chatbot('노력해도 안되더라')
print(label)
print(ans)

<unused0>노력해도 안되더라<unused1>
--------------------------------------------------
tf.Tensor([[    1     9 10805 12704  9183  7251  7208  7372    10]], shape=(1, 9), dtype=int32)
tf.Tensor(
[[    1     9 10805 12704  9183  7251  7208  7372    10 14771   390 26396
   7416    11 29205  9723 11392  6872  8006 25856 45887 42783 15453  9183
   7251  6872  8006  8084   376    10 14771 46623  8148  6830    11 29205
  20164  6872  8006 13704 45887 42783  9723 11392  7532 45887 42783 45887
  15453  9183  7965 25856     1]], shape=(1, 53), dtype=int32)
##################################################
</s><unused0> 노력해도 안되더라<unused1> 증상/무기력<unused2> 정말 힘드시겠어요. 제가 옆에서 힘이 안되겠어요!<unused1> 증상/이인감<unused2> 정말 힘들겠어요, 제가 옆에서 힘드시면 제가 옆에서 제가 힘이 안아요.</s>
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
증상/무기력
정말 힘드시겠어요. 제가 옆에서 힘이 안되겠어요!


In [ ]:
label, ans = chatbot('먹어도 먹어도 아주 배고파요')
print(label)
print(ans)

증상/ 배고픔
정말 배고프셨겠어요. 증상/배고픔/배부르셨어


In [ ]:
label, ans = chatbot('수강신청을 망쳐서 휴학을 하고 싶어요')
print(label)
print(ans)

증상/휴학/휴학을/신청
휴학을 하셨군요. 긴 휴식이 필요할 때가 있죠. 괜찮으세요?


In [ ]:
label, ans = chatbot('남친이랑 어젯밤에 싸웠어요')
print(label)
print(ans)

증상/어지러움/생리불순/생리적
정말 걱정이 많으시겠어요. 하지만 정말 걱정은 많으세요?


In [ ]:
label, ans = chatbot('데이터 분석 공부 넘 어려워요. 포기하고 싶어요')
print(label)
print(ans)

증상/무기력
정말 힘드시겠어요. 제가 옆에서 힘이 되어 드릴게요.


In [ ]:
# for _ in range(15):
#     print(f'# {_} :', tokenizer.decode(_))

In [ ]:
from transformers import PreTrainedTokenizerFast
tokenizer = PreTrainedTokenizerFast.from_pretrained("skt/kogpt2-base-v2",
bos_token='</s>', eos_token='</s>', unk_token='<unk>',
pad_token='<pad>', mask_token='<mask>')
tokenizer.tokenize("안녕하세요. 한국어 GPT-2 입니다.😤:)l^o")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPT2Tokenizer'. 
The class this function is called from is 'PreTrainedTokenizerFast'.


['▁안녕',
 '하',
 '세',
 '요.',
 '▁한국어',
 '▁G',
 'P',
 'T',
 '-2',
 '▁입',
 '니다.',
 '😤',
 ':)',
 'l^o']

In [ ]:
import torch
from transformers import GPT2LMHeadModel

model = GPT2LMHeadModel.from_pretrained('skt/kogpt2-base-v2')
text = '어제 남친이랑 싸워서 속상해'
input_ids = tokenizer.encode(text, return_tensors='pt')
gen_ids = model.generate(input_ids,
                           max_length=128,
                           repetition_penalty=2.0,
                           pad_token_id=tokenizer.pad_token_id,
                           eos_token_id=tokenizer.eos_token_id,
                           bos_token_id=tokenizer.bos_token_id,
                           use_cache=True)
generated = tokenizer.decode(gen_ids[0])
print(generated)

어제 남친이랑 싸워서 속상해하고 있거든요.
그런데 그게 사실 뭐냐면 이~ 저기 우리 김정은 위원장이 지금 이제 북한을 방문해서 어딘가에 있는 어떤 호텔에 묵고 있는데 네. 거기서 또 다른 사람이 와서 이렇게 얘기를 하고 있어요.
네. 그래서 인제 그런 일이 벌어졌다라고 하는 거죠.
예? 예?
어떻든 간에 아까 말씀드린 것처럼 북한이 굉장히 좀 예민한 반응을 보이고 있습니다.
아니 근데는 왜 그러느냐 하면 북한은 이미 핵실험과 미사일 발사를 했고 그리고 지난 십일월에는 사십오 일날 노동당 창건 기념 열병
